### PR TITLE
Add russian documentation.

### PR DESCRIPTION
**Pull request by Him4enko**

### CODE REVIEW

**Comment by hide-me** [comment]
That's really great!

Thanks a lot for contributing and the beginning of documentation on Russian. You already did a big job and the quality of translation is good.

I noticed you did very few typos, but now I'm really busy. Well, I hope, I will fix typos at the end of August. Sorry, for this delayed fixing.

@dignajar **FOR SURE merge it**, please!

**Comment by dignajar** [comment]
Thank you guys for the support and the work!

**Comment by dignajar** [comment]
I need to do some modifications in the server to shows up the documentation, I will work tonight on it.

**Comment by Him4enko** [comment]
> That's really great!
> 
> Thanks a lot for contributing and the beginning of documentation on Russian. You already did a big job and the quality of translation is good.
> 
> I noticed you did very few typos, but now I'm really busy. Well, I hope, I will fix typos at the end of August. Sorry, for this delayed fixing.
> 
> @dignajar **FOR SURE merge it**, please!

К сожалению, моя первая работа по переводу. К сожалению, действительно там есть некоторое число опечаток и недочетов, но я могу это описать нехваткой примеров. Я думаю, что вы исправите недочеты, если заметите. :)

**Pull request merged**
